#+TITLE: Exercises for Python
#+AUTHOR: YN
* Bronze
Write a program that asks the user to input an integer, and then for each number from 1 to the user-entered integer, print it out on a separate line. Here's the starting point for the file =bronze.py=
#+INCLUDE: "bronze.py" src python
Sample interaction:
#+BEGIN_EXAMPLE
∴ python bronze.py
Please enter a number: 10
1
2
3
4
5
6
7
8
9
10
#+END_EXAMPLE
* Silver
Write a program that continually (in a loop) asks the user to input a number. Print out that number back, except that if the user entered a number that is divisible by 3, you print out "Fizz", and if the user entered a number that is divisible by 5, you print out "Buzz". If the user entered a number that is divisible by both 3 and 5, then you print out "FizzBuzz". Here's the starting point for the file =silver.py=:
#+INCLUDE: "silver.py" src python
Sample interaction:
#+BEGIN_EXAMPLE
∴ python silver.py
Please enter a number: 2
2
Please enter a number: 3
Fizz
Please enter a number: 5
Buzz
Please enter a number: 15
FizzBuzz
Please enter a number: 16
16
Please enter a number: CTRL-C
#+END_EXAMPLE
* Gold
Write a program that doesn't ask for any user input, which means that it always does the same thing, which is: go from number 1 to number 100, and for each one of those numbers, print it on a separate line, except if the number is divisible by 3, print out "Fizz" instead of the number, and if the number is divisible by 5, print out "Buzz" instead of the number, and if the number is divisible by both 3 and 5, then print out FizzBuzz instead of the number. Here's the starting point for the file =gold.py=:
#+INCLUDE: "gold.py" src python
Sample interaction:
#+BEGIN_EXAMPLE
∴ python gold.py
1
2
Fizz
4
Buzz
...
14
FizzBuzz
16
...
29
FizzBuzz
31
...
97
98
Fizz
Buzz
#+END_EXAMPLE
* Platinum 1
Write a program that asks the user to enter a number X. Then, print out a triangle of stars, where the first line has X stars, and the next line has X - 1 stars, until there are no more stars left.
#+INCLUDE: "platinum.py" src python
Sample interaction
#+BEGIN_EXAMPLE
∴ python platinum.py
Please enter the length of the side of the triangle: 5
*****
****
***
**
*
#+END_EXAMPLE
* Platinum 2
Redo "Platinum 1", but you are not allowed to use the Python built-in "string multiplication" operation.
* Platinum 3
Redo "Platinum 1", but you are not allowed to use either the Python built-in "string multiplication" operation, or the range() function.

